FDS_IRQ_RELOAD_LOW = $4020
FDS_IRQ_RELOAD_HIGH = $4021
FDS_IRQ_CONTROL = $4022
FDS_CONTROL  = $4024
FDS_DISK_STATUS = $4030
FDS_DRIVE_STATUS = $4032


IsWindy = $0717 ; Old DemoAction
FdsOperTask = $07FC				; SMB2J
; WaitForIRQ = $077B				; SMB2J ; KILLED.
; LoadListIndex = $07f7			; SMB2J KILLED
FdsBiosIrqAction = $101			; SMB2J
FdsLastWrite4025 = $fa			; SMB2J
UseNtBase2400 = $77a			; SMB2J
IsPlayingExtendedWorlds = $7FB	; SMB2J
byte_7F5 = $7f5 ; what is this...?
WorldsCompleted = $7f7 ; Moved from 7FA (think there is other shit there ;))

; ContinueWorld is killed too
; Old LOST timer:
; byte_7EC = $7ec ; KILLED
; byte_7ED = $7ed ; KILLED
; byte_7EE = $7ee ; KILLED
; </timer> 

; byte_7FA = $7fa; KILLED. WorldsCompleted
; byte_7F9 = $7f9; KILLED
; GameTimerDisplay_OBSOLETE = $07f8 ; KILLED.

byte_2 = $2
byte_3 = $3
byte_4 = $4
byte_5 = $5
byte_6 = $6
unk_7 = $7

byte_14 = $14
byte_1B = $1b
byte_23 = $23
byte_73 = $73
byte_8C = $8c
byte_BB = $bb
byte_D4 = $d4
byte_EB = $eb
byte_EC = $ec
byte_ED = $ed
byte_EF = $ef
byte_138 = $138
byte_139 = $139
byte_1A9 = $1a9
byte_207 = $207
byte_222 = $222
byte_226 = $226
byte_2A9 = $2a9
byte_308 = $308
byte_309 = $309
byte_314 = $314
byte_316 = $316
byte_31C = $31c
byte_3A9 = $3a9
byte_3B2 = $3b2
byte_3BD = $3bd
byte_3CA = $3ca
byte_49F = $49f
byte_4A9 = $4a9
byte_5B4 = $5b4
unk_6A2 = $6a2
byte_6A8 = $6a8
byte_6AB = $6ab
byte_6C9 = $6c9
byte_6E2 = $6e2
byte_6E3 = $6e3
unk_6E9 = $6e9
byte_6EA = $6ea
unk_6F2 = $6f2
byte_731 = $731
byte_732 = $732
byte_7A9 = $7a9
byte_7F6 = $7f6
byte_7E7 = $7e7
byte_7E8 = $7e8
byte_6EB = $6eb

TMP_0 = $0
TMP_1 = $1

